### PR TITLE
Perform Exploratory Data Analysis #18

### PR DESCRIPTION
**Pull request by Dishant-garg**
solved issue #18 
use the value_counts function and idxmax fucntion to solve the issue properly according to the needs asked by issue
Screenshot (471)
Screenshot (472)
Screenshot (473)
Screenshot (474)
Screenshot (475)

### CODE REVIEW

**Comment by mitalijambhulkar67** [comment]
Data visualization is an important component of Exploratory Data Analysis (EDA). Please make sure you did it too.

**Comment by Dishant-garg** [comment]
https://colab.research.google.com/drive/1bbpIXXRe-iPdvQ2N1hGfQwvZsucz5QO6#scrollTo=qCRwSAtyF30O
tup
second
fourth
fifth
third

**Comment by Dishant-garg** [comment]
@mitalijambhulkar67 pls check new collab file done with visualization also

**Comment by mitalijambhulkar67** [comment]
Push and commit the colab notebook.

**Pull request merged**
